name = "na-scheduleshare-import"
main = "src/index.ts"
compatibility_date = "2026-07-16"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "adbf10df0aec463f832dbe4cd8f2e76c""
preview_id = "50dc62af983a4f69a91a89aed2a56a4e"

[vars]
RATE_LIMIT_MAX = "6"
RATE_LIMIT_WINDOW_SECONDS = "3600"

[secrets]
required = ["SUPABASE_URL", "SUPABASE_PUBLISHABLE_KEY"]
